# Generated by Django 4.1.3 on 2022-12-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='registroclientetienda',
            options={'verbose_name': 'registroclientetienda'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='tiendas',
            options={'verbose_name': 'tiendas'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'usuarios'},
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'verbose_name': 'ventas'},
        ),
    ]
