# Generated by Django 4.1.3 on 2022-12-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_productos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='registroclientetienda',
            table='registroclientetienda',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='tiendas',
            table='tiendas',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
        migrations.AlterModelTable(
            name='ventas',
            table='ventas',
        ),
    ]
